; Processor load, package temperature and used memory, in one line.

[module/cpu]
type                            = custom/script
interval                        = 2

exec                            = ~/.config/polybar/scripts/cpu.sh

format                          = <label>
label                           = %output%

format-foreground               = ${colors.foreground}
format-background               = ${colors.background}
format-underline                = ${colors.accent-system}
