; Dunst state. A click pauses or resumes notifications.

[module/dunst]
type                            = custom/script
interval                        = 2

exec                            = ~/.config/polybar/scripts/dunst.sh

format                          = <label>
label                           = %output%

format-foreground               = ${colors.foreground}
format-background               = ${colors.background}

click-left                      = ~/.config/polybar/scripts/dunst.sh --toggle &
