; Opens the rofi power menu.

[module/powermenu]
type                            = custom/text

format                          = <label>
label                           = %{T2}󰤆%{T-}

format-foreground               = ${colors.alert}
format-background               = ${colors.background}

click-left                      = ~/.config/polybar/scripts/powermenu.sh &
