; Vertical rule placed between module groups.

[module/sep]
type                            = custom/text

format                          = <label>
label                           = |

label-foreground                = ${colors.separator}
