; Title of the focused window.

[module/xwindow]
type                            = internal/xwindow

format                          = <label>
label                           = %title%
label-maxlen                    = 20

format-foreground               = ${colors.foreground}
format-background               = ${colors.background}
